// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using MiCv.Data.Databases.MiCv;
using Microsoft.EntityFrameworkCore;

namespace MiCv.Data.Databases.MiCv.Context;

public partial class MiCvContext : DbContext
{
    public MiCvContext()
    {
    }

    public MiCvContext(DbContextOptions<MiCvContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Certificacion> Certificacion { get; set; }

    public virtual DbSet<Curso> Curso { get; set; }

    public virtual DbSet<DatoContacto> DatoContacto { get; set; }

    public virtual DbSet<ExperienciaLaboral> ExperienciaLaboral { get; set; }

    public virtual DbSet<ExperienciaResponsabilidad> ExperienciaResponsabilidad { get; set; }

    public virtual DbSet<FormacionAcademica> FormacionAcademica { get; set; }

    public virtual DbSet<Habilidad> Habilidad { get; set; }

    public virtual DbSet<Idioma> Idioma { get; set; }

    public virtual DbSet<PerfilProfesional> PerfilProfesional { get; set; }

    public virtual DbSet<Persona> Persona { get; set; }

    public virtual DbSet<PersonaHabilidad> PersonaHabilidad { get; set; }

    public virtual DbSet<PersonaIdioma> PersonaIdioma { get; set; }

    public virtual DbSet<PersonaLink> PersonaLink { get; set; }

    public virtual DbSet<Proyecto> Proyecto { get; set; }

    public virtual DbSet<ProyectoHabilidad> ProyectoHabilidad { get; set; }

    public virtual DbSet<Publicacion> Publicacion { get; set; }

    public virtual DbSet<Reconocimiento> Reconocimiento { get; set; }

    public virtual DbSet<Referencia> Referencia { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=108.181.157.254,10063;Initial Catalog=MiCv;Persist Security Info=True;User ID=CvUser;Password=!H[q}yGbzGse@bL[t;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Certificacion>(entity =>
        {
            entity.HasIndex(e => e.EntidadEmisora, "IX_Certificacion_EntidadEmisora");

            entity.HasIndex(e => e.PersonaId, "IX_Certificacion_PersonaId");

            entity.HasIndex(e => new { e.PersonaId, e.FechaEmision }, "IX_Certificacion_PersonaId_FechaEmision").IsDescending(false, true);

            entity.Property(e => e.CodigoCredencial).HasMaxLength(150);
            entity.Property(e => e.EntidadEmisora)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FechaEmision).HasColumnType("date");
            entity.Property(e => e.FechaExpiracion).HasColumnType("date");
            entity.Property(e => e.LinkCredencial).HasMaxLength(500);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Persona).WithMany(p => p.Certificacion)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_Certificacion_Persona");
        });

        modelBuilder.Entity<Curso>(entity =>
        {
            entity.HasIndex(e => e.Institucion, "IX_Curso_Institucion");

            entity.HasIndex(e => e.PersonaId, "IX_Curso_PersonaId");

            entity.HasIndex(e => new { e.PersonaId, e.FechaInicio, e.FechaFin }, "IX_Curso_PersonaId_Fechas").IsDescending(false, true, true);

            entity.Property(e => e.FechaFin).HasColumnType("date");
            entity.Property(e => e.FechaInicio).HasColumnType("date");
            entity.Property(e => e.Horas).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Institucion).HasMaxLength(200);
            entity.Property(e => e.LinkCertificado).HasMaxLength(500);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Plataforma).HasMaxLength(150);

            entity.HasOne(d => d.Persona).WithMany(p => p.Curso)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_Curso_Persona");
        });

        modelBuilder.Entity<DatoContacto>(entity =>
        {
            entity.HasIndex(e => e.PersonaId, "IX_DatoContacto_PersonaId");

            entity.HasIndex(e => e.TipoContacto, "IX_DatoContacto_TipoContacto");

            entity.Property(e => e.TipoContacto)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Valor)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.Persona).WithMany(p => p.DatoContacto)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_DatoContacto_Persona");
        });

        modelBuilder.Entity<ExperienciaLaboral>(entity =>
        {
            entity.HasIndex(e => e.Empresa, "IX_ExperienciaLaboral_Empresa");

            entity.HasIndex(e => e.PersonaId, "IX_ExperienciaLaboral_PersonaId");

            entity.HasIndex(e => new { e.PersonaId, e.Actualmente, e.FechaInicio, e.FechaFin }, "IX_ExperienciaLaboral_PersonaId_Fechas").IsDescending(false, true, true, true);

            entity.Property(e => e.Cargo)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Empresa)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FechaFin).HasColumnType("date");
            entity.Property(e => e.FechaInicio).HasColumnType("date");
            entity.Property(e => e.Modalidad).HasMaxLength(50);
            entity.Property(e => e.TipoContrato).HasMaxLength(50);
            entity.Property(e => e.Ubicacion).HasMaxLength(150);

            entity.HasOne(d => d.Persona).WithMany(p => p.ExperienciaLaboral)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_ExperienciaLaboral_Persona");
        });

        modelBuilder.Entity<ExperienciaResponsabilidad>(entity =>
        {
            entity.HasIndex(e => e.ExperienciaLaboralId, "IX_ExperienciaResponsabilidad_ExperienciaLaboralId");

            entity.HasIndex(e => new { e.ExperienciaLaboralId, e.Orden }, "IX_ExperienciaResponsabilidad_ExperienciaLaboralId_Orden");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.ExperienciaLaboral).WithMany(p => p.ExperienciaResponsabilidad)
                .HasForeignKey(d => d.ExperienciaLaboralId)
                .HasConstraintName("FK_ExperienciaResponsabilidad_ExperienciaLaboral");
        });

        modelBuilder.Entity<FormacionAcademica>(entity =>
        {
            entity.HasIndex(e => e.Institucion, "IX_FormacionAcademica_Institucion");

            entity.HasIndex(e => e.PersonaId, "IX_FormacionAcademica_PersonaId");

            entity.HasIndex(e => new { e.PersonaId, e.Actualmente, e.FechaInicio, e.FechaFin }, "IX_FormacionAcademica_PersonaId_Fechas").IsDescending(false, true, true, true);

            entity.Property(e => e.AreaEstudio).HasMaxLength(150);
            entity.Property(e => e.FechaFin).HasColumnType("date");
            entity.Property(e => e.FechaInicio).HasColumnType("date");
            entity.Property(e => e.Institucion)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NivelAcademico).HasMaxLength(100);
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Ubicacion).HasMaxLength(150);

            entity.HasOne(d => d.Persona).WithMany(p => p.FormacionAcademica)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_FormacionAcademica_Persona");
        });

        modelBuilder.Entity<Habilidad>(entity =>
        {
            entity.HasIndex(e => e.Categoria, "IX_Habilidad_Categoria");

            entity.HasIndex(e => e.Nombre, "UX_Habilidad_Nombre").IsUnique();

            entity.Property(e => e.Categoria).HasMaxLength(100);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Idioma>(entity =>
        {
            entity.HasIndex(e => e.Nombre, "UX_Idioma_Nombre").IsUnique();

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<PerfilProfesional>(entity =>
        {
            entity.HasIndex(e => e.PersonaId, "UX_PerfilProfesional_PersonaId").IsUnique();

            entity.Property(e => e.AniosExperiencia).HasColumnType("decimal(4, 1)");
            entity.Property(e => e.EspecialidadPrincipal).HasMaxLength(150);
            entity.Property(e => e.Resumen).IsRequired();

            entity.HasOne(d => d.Persona).WithOne(p => p.PerfilProfesional)
                .HasForeignKey<PerfilProfesional>(d => d.PersonaId)
                .HasConstraintName("FK_PerfilProfesional_Persona");
        });

        modelBuilder.Entity<Persona>(entity =>
        {
            entity.HasIndex(e => new { e.Apellidos, e.Nombres }, "IX_Persona_Apellidos_Nombres");

            entity.Property(e => e.Apellidos)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Ciudad).HasMaxLength(100);
            entity.Property(e => e.FechaNacimiento).HasColumnType("date");
            entity.Property(e => e.LinkPerfil).HasMaxLength(500);
            entity.Property(e => e.Nacionalidad).HasMaxLength(100);
            entity.Property(e => e.Nombres)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Pais).HasMaxLength(100);
            entity.Property(e => e.ResumenCorto).HasMaxLength(300);
            entity.Property(e => e.TituloProfesional).HasMaxLength(150);

            entity.HasOne(d => d.Usuario).WithMany(p => p.Persona)
                .HasForeignKey(d => d.UsuarioId)
                .HasConstraintName("FK_Persona_Usuario");
        });

        modelBuilder.Entity<PersonaHabilidad>(entity =>
        {
            entity.HasIndex(e => e.HabilidadId, "IX_PersonaHabilidad_HabilidadId");

            entity.HasIndex(e => e.PersonaId, "IX_PersonaHabilidad_PersonaId");

            entity.HasIndex(e => new { e.PersonaId, e.EsPrincipal }, "IX_PersonaHabilidad_PersonaId_EsPrincipal");

            entity.HasIndex(e => new { e.PersonaId, e.HabilidadId }, "UX_PersonaHabilidad_PersonaId_HabilidadId").IsUnique();

            entity.Property(e => e.AniosExperiencia).HasColumnType("decimal(4, 1)");
            entity.Property(e => e.Nivel).HasMaxLength(50);

            entity.HasOne(d => d.Habilidad).WithMany(p => p.PersonaHabilidad)
                .HasForeignKey(d => d.HabilidadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonaHabilidad_Habilidad");

            entity.HasOne(d => d.Persona).WithMany(p => p.PersonaHabilidad)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_PersonaHabilidad_Persona");
        });

        modelBuilder.Entity<PersonaIdioma>(entity =>
        {
            entity.HasIndex(e => e.IdiomaId, "IX_PersonaIdioma_IdiomaId");

            entity.HasIndex(e => e.PersonaId, "IX_PersonaIdioma_PersonaId");

            entity.HasIndex(e => new { e.PersonaId, e.IdiomaId }, "UX_PersonaIdioma_PersonaId_IdiomaId").IsUnique();

            entity.Property(e => e.Certificacion).HasMaxLength(150);
            entity.Property(e => e.NivelConversacion).HasMaxLength(50);
            entity.Property(e => e.NivelEscritura).HasMaxLength(50);
            entity.Property(e => e.NivelGeneral).HasMaxLength(50);
            entity.Property(e => e.NivelLectura).HasMaxLength(50);

            entity.HasOne(d => d.Idioma).WithMany(p => p.PersonaIdioma)
                .HasForeignKey(d => d.IdiomaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonaIdioma_Idioma");

            entity.HasOne(d => d.Persona).WithMany(p => p.PersonaIdioma)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_PersonaIdioma_Persona");
        });

        modelBuilder.Entity<PersonaLink>(entity =>
        {
            entity.HasIndex(e => e.PersonaId, "IX_PersonaLink_PersonaId");

            entity.HasIndex(e => e.TipoLink, "IX_PersonaLink_TipoLink");

            entity.Property(e => e.TextoVisible).HasMaxLength(150);
            entity.Property(e => e.TipoLink)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.Persona).WithMany(p => p.PersonaLink)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_PersonaLink_Persona");
        });

        modelBuilder.Entity<Proyecto>(entity =>
        {
            entity.HasIndex(e => e.PersonaId, "IX_Proyecto_PersonaId");

            entity.HasIndex(e => new { e.PersonaId, e.Actualmente, e.FechaInicio, e.FechaFin }, "IX_Proyecto_PersonaId_Fechas").IsDescending(false, true, true, true);

            entity.Property(e => e.ClienteEmpresa).HasMaxLength(200);
            entity.Property(e => e.FechaFin).HasColumnType("date");
            entity.Property(e => e.FechaInicio).HasColumnType("date");
            entity.Property(e => e.LinkDemo).HasMaxLength(500);
            entity.Property(e => e.LinkRepositorio).HasMaxLength(500);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Rol).HasMaxLength(150);

            entity.HasOne(d => d.Persona).WithMany(p => p.Proyecto)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_Proyecto_Persona");
        });

        modelBuilder.Entity<ProyectoHabilidad>(entity =>
        {
            entity.HasIndex(e => e.HabilidadId, "IX_ProyectoHabilidad_HabilidadId");

            entity.HasIndex(e => e.ProyectoId, "IX_ProyectoHabilidad_ProyectoId");

            entity.HasIndex(e => new { e.ProyectoId, e.HabilidadId }, "UX_ProyectoHabilidad_ProyectoId_HabilidadId").IsUnique();

            entity.HasOne(d => d.Habilidad).WithMany(p => p.ProyectoHabilidad)
                .HasForeignKey(d => d.HabilidadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProyectoHabilidad_Habilidad");

            entity.HasOne(d => d.Proyecto).WithMany(p => p.ProyectoHabilidad)
                .HasForeignKey(d => d.ProyectoId)
                .HasConstraintName("FK_ProyectoHabilidad_Proyecto");
        });

        modelBuilder.Entity<Publicacion>(entity =>
        {
            entity.HasIndex(e => e.PersonaId, "IX_Publicacion_PersonaId");

            entity.HasIndex(e => new { e.PersonaId, e.FechaPublicacion }, "IX_Publicacion_PersonaId_FechaPublicacion").IsDescending(false, true);

            entity.Property(e => e.FechaPublicacion).HasColumnType("date");
            entity.Property(e => e.LinkPublicacion).HasMaxLength(500);
            entity.Property(e => e.Medio).HasMaxLength(200);
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.Persona).WithMany(p => p.Publicacion)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_Publicacion_Persona");
        });

        modelBuilder.Entity<Reconocimiento>(entity =>
        {
            entity.HasIndex(e => e.PersonaId, "IX_Reconocimiento_PersonaId");

            entity.HasIndex(e => new { e.PersonaId, e.Fecha }, "IX_Reconocimiento_PersonaId_Fecha").IsDescending(false, true);

            entity.Property(e => e.Entidad).HasMaxLength(200);
            entity.Property(e => e.Fecha).HasColumnType("date");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Persona).WithMany(p => p.Reconocimiento)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_Reconocimiento_Persona");
        });

        modelBuilder.Entity<Referencia>(entity =>
        {
            entity.HasIndex(e => e.PersonaId, "IX_Referencia_PersonaId");

            entity.Property(e => e.Cargo).HasMaxLength(150);
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.Empresa).HasMaxLength(200);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Relacion).HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(50);

            entity.HasOne(d => d.Persona).WithMany(p => p.Referencia)
                .HasForeignKey(d => d.PersonaId)
                .HasConstraintName("FK_Referencia_Persona");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.Property(e => e.Contrasenna)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Correo)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}