// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Certificacion
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string Nombre { get; set; }

    public string EntidadEmisora { get; set; }

    public DateTime? FechaEmision { get; set; }

    public DateTime? FechaExpiracion { get; set; }

    public string CodigoCredencial { get; set; }

    public string LinkCredencial { get; set; }

    public string Descripcion { get; set; }

    public int? Orden { get; set; }

    public virtual Persona Persona { get; set; }
}