// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Curso
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string Nombre { get; set; }

    public string Institucion { get; set; }

    public string Plataforma { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public decimal? Horas { get; set; }

    public string LinkCertificado { get; set; }

    public string Descripcion { get; set; }

    public int? Orden { get; set; }

    public virtual Persona Persona { get; set; }
}