// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class DatoContacto
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string TipoContacto { get; set; }

    public string Valor { get; set; }

    public bool EsPrincipal { get; set; }

    public bool EsPublico { get; set; }

    public virtual Persona Persona { get; set; }
}