// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class ExperienciaResponsabilidad
{
    public int Id { get; set; }

    public int ExperienciaLaboralId { get; set; }

    public string Descripcion { get; set; }

    public int Orden { get; set; }

    public virtual ExperienciaLaboral ExperienciaLaboral { get; set; }
}