// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class ExperienciaLaboral
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string Empresa { get; set; }

    public string Cargo { get; set; }

    public string Ubicacion { get; set; }

    public string Modalidad { get; set; }

    public string TipoContrato { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public bool Actualmente { get; set; }

    public string Descripcion { get; set; }

    public string Logros { get; set; }

    public int? Orden { get; set; }

    public virtual ICollection<ExperienciaResponsabilidad> ExperienciaResponsabilidad { get; set; } = new List<ExperienciaResponsabilidad>();

    public virtual Persona Persona { get; set; }
}