// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class FormacionAcademica
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string Institucion { get; set; }

    public string Titulo { get; set; }

    public string AreaEstudio { get; set; }

    public string NivelAcademico { get; set; }

    public string Ubicacion { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public bool Actualmente { get; set; }

    public string Descripcion { get; set; }

    public int? Orden { get; set; }

    public virtual Persona Persona { get; set; }
}