// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Habilidad
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Categoria { get; set; }

    public virtual ICollection<PersonaHabilidad> PersonaHabilidad { get; set; } = new List<PersonaHabilidad>();

    public virtual ICollection<ProyectoHabilidad> ProyectoHabilidad { get; set; } = new List<ProyectoHabilidad>();
}