// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Idioma
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<PersonaIdioma> PersonaIdioma { get; set; } = new List<PersonaIdioma>();
}