// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class PerfilProfesional
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string Resumen { get; set; }

    public string ObjetivoProfesional { get; set; }

    public decimal? AniosExperiencia { get; set; }

    public string EspecialidadPrincipal { get; set; }

    public virtual Persona Persona { get; set; }
}