// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class PersonaLink
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string TipoLink { get; set; }

    public string Url { get; set; }

    public string TextoVisible { get; set; }

    public bool EsPrincipal { get; set; }

    public int Orden { get; set; }

    public virtual Persona Persona { get; set; }
}