// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class PersonaHabilidad
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public int HabilidadId { get; set; }

    public string Nivel { get; set; }

    public decimal? AniosExperiencia { get; set; }

    public bool EsPrincipal { get; set; }

    public int Orden { get; set; }

    public virtual Habilidad Habilidad { get; set; }

    public virtual Persona Persona { get; set; }
}