// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Persona
{
    public int Id { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string TituloProfesional { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public string Nacionalidad { get; set; }

    public string Ciudad { get; set; }

    public string Pais { get; set; }

    public string LinkPerfil { get; set; }

    public string ResumenCorto { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public int? UsuarioId { get; set; }

    public virtual ICollection<Certificacion> Certificacion { get; set; } = new List<Certificacion>();

    public virtual ICollection<Curso> Curso { get; set; } = new List<Curso>();

    public virtual ICollection<DatoContacto> DatoContacto { get; set; } = new List<DatoContacto>();

    public virtual ICollection<ExperienciaLaboral> ExperienciaLaboral { get; set; } = new List<ExperienciaLaboral>();

    public virtual ICollection<FormacionAcademica> FormacionAcademica { get; set; } = new List<FormacionAcademica>();

    public virtual PerfilProfesional PerfilProfesional { get; set; }

    public virtual ICollection<PersonaHabilidad> PersonaHabilidad { get; set; } = new List<PersonaHabilidad>();

    public virtual ICollection<PersonaIdioma> PersonaIdioma { get; set; } = new List<PersonaIdioma>();

    public virtual ICollection<PersonaLink> PersonaLink { get; set; } = new List<PersonaLink>();

    public virtual ICollection<Proyecto> Proyecto { get; set; } = new List<Proyecto>();

    public virtual ICollection<Publicacion> Publicacion { get; set; } = new List<Publicacion>();

    public virtual ICollection<Reconocimiento> Reconocimiento { get; set; } = new List<Reconocimiento>();

    public virtual ICollection<Referencia> Referencia { get; set; } = new List<Referencia>();

    public virtual Usuario Usuario { get; set; }
}