// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class PersonaIdioma
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public int IdiomaId { get; set; }

    public string NivelLectura { get; set; }

    public string NivelEscritura { get; set; }

    public string NivelConversacion { get; set; }

    public string NivelGeneral { get; set; }

    public string Certificacion { get; set; }

    public int Orden { get; set; }

    public virtual Idioma Idioma { get; set; }

    public virtual Persona Persona { get; set; }
}