// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Proyecto
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string Nombre { get; set; }

    public string Rol { get; set; }

    public string ClienteEmpresa { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public bool Actualmente { get; set; }

    public string Descripcion { get; set; }

    public string LinkRepositorio { get; set; }

    public string LinkDemo { get; set; }

    public int? Orden { get; set; }

    public virtual Persona Persona { get; set; }

    public virtual ICollection<ProyectoHabilidad> ProyectoHabilidad { get; set; } = new List<ProyectoHabilidad>();
}