// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class ProyectoHabilidad
{
    public int Id { get; set; }

    public int ProyectoId { get; set; }

    public int HabilidadId { get; set; }

    public virtual Habilidad Habilidad { get; set; }

    public virtual Proyecto Proyecto { get; set; }
}