// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Publicacion
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string Titulo { get; set; }

    public string Medio { get; set; }

    public DateTime? FechaPublicacion { get; set; }

    public string LinkPublicacion { get; set; }

    public string Descripcion { get; set; }

    public virtual Persona Persona { get; set; }
}