// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Reconocimiento
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string Nombre { get; set; }

    public string Entidad { get; set; }

    public DateTime? Fecha { get; set; }

    public string Descripcion { get; set; }

    public virtual Persona Persona { get; set; }
}