// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Referencia
{
    public int Id { get; set; }

    public int PersonaId { get; set; }

    public string Nombre { get; set; }

    public string Cargo { get; set; }

    public string Empresa { get; set; }

    public string Email { get; set; }

    public string Telefono { get; set; }

    public string Relacion { get; set; }

    public bool DisponiblePreviaSolicitud { get; set; }

    public virtual Persona Persona { get; set; }
}