// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiCv.Data.Databases.MiCv;

public partial class Usuario
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Correo { get; set; }

    public string Contrasenna { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<Persona> Persona { get; set; } = new List<Persona>();
}